apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: nginx
  name: nginx-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: pvc-one
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: nfs-vol
          mountPath: /opt
status: {}
