apiVersion: v1
kind: Pod
metadata:
  name: vip
spec:
  # nodeSelector:
  #   status: vip
  containers:
  - name: vip
    image: busybox
    args: 
      - sleep
      - "100000"
  - name: vip2
    image: busybox
    args: 
      - sleep
      - "100000"
  - name: vip3
    image: busybox
    args: 
      - sleep
      - "100000"