apiVersion: v1
kind: Pod
metadata:
  name: other
spec:
  nodeSelector:
    status: other
  containers:
  - name: vip
    image: busybox
    args: 
      - sleep
      - "100000"
  - name: vip2
    image: busybox
    args: 
      - sleep
      - "100000"
  - name: vip3
    image: busybox
    args: 
      - sleep
      - "100000"
