apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: resting
spec: 
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 15
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: resting
        command: ["/bin/sleep"]
        args: ["5"]
      restartPolicy: Never
